config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :Contact
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :Kindo
end

app/models/kind.rb
class Kind < ActiveRecord::Base
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :city, :state, :Contact_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:nome, :email, :Kindo_id, :rmk)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index
    @nome = "Paulo Ricardo";
    @kinds = Kind.all
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: 'Kind was successfully updated.' }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: 'Kind was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url, notice: 'Phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_params
      params.require(:phone).permit(:phone, :contact_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
    def mostrar_meu_nome
        "Paulo Ricardo"
    end
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :Contact_id %><br>
    <%= f.text_field :Contact_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.street %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= address.Contact %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @address.Contact %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :Kind_id %><br>
    <%= f.text_field :Kind_id %>
  </div>
  <div class="field">
    <%= f.label :rmk %><br>
    <%= f.text_area :rmk %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Kindo</th>
      <th>Rmk</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.nome %></td>
        <td><%= contact.email %></td>
        <td><%= contact.Kindo %></td>
        <td><%= contact.rmk %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contact.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Kindo:</strong>
  <%= @contact.Kindo %>
</p>

<p>
  <strong>Rmk:</strong>
  <%= @contact.rmk %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/index.html.erb
<h1>Seja bem bindo, <%= mostrar_meu_nome %></h1>


<ul>
    <li><%= link_to "Tipos", kinds_path %></li>
    <li><%= link_to "Telefones", phones_path%></li>
    <li><%= link_to "Endereços", addresses_path%></li>
    <li><%= link_to "Contatos", contacts_path%></li>
</ul>

app/views/kinds/_form.html.erb
<%= form_for(@kind) do |f| %>
  <% if @kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
      <% @kind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<h1>Editing Kind</h1>

<%= render 'form' %>

<%= link_to 'Show', @kind %> |
<%= link_to 'Back', kinds_path %>

app/views/kinds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando os tipos - <%= @nome %></h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kinds.each do |kind| %>
      <tr>
        <td><%= kind.description %></td>
        <td><%= link_to 'Show', kind %></td>
        <td><%= link_to 'Edit', edit_kind_path(kind) %></td>
        <td><%= link_to 'Destroy', kind, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kind', new_kind_path %>

app/views/kinds/new.html.erb
<h1>New Kind</h1>

<%= render 'form' %>

<%= link_to 'Back', kinds_path %>

app/views/kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @kind.description %>
</p>

<%= link_to 'Edit', edit_kind_path(@kind) %> |
<%= link_to 'Back', kinds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nootbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/phones/_form.html.erb
<%= form_for(@phone) do |f| %>
  <% if @phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% @phone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :contact_id %><br>
    <%= f.text_field :contact_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phones/edit.html.erb
<h1>Editing Phone</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone %> |
<%= link_to 'Back', phones_path %>

app/views/phones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Phones</h1>

<table>
  <thead>
    <tr>
      <th>Phone</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phones.each do |phone| %>
      <tr>
        <td><%= phone.phone %></td>
        <td><%= phone.contact %></td>
        <td><%= link_to 'Show', phone %></td>
        <td><%= link_to 'Edit', edit_phone_path(phone) %></td>
        <td><%= link_to 'Destroy', phone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone', new_phone_path %>

app/views/phones/new.html.erb
<h1>New Phone</h1>

<%= render 'form' %>

<%= link_to 'Back', phones_path %>

app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone:</strong>
  <%= @phone.phone %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @phone.contact %>
</p>

<%= link_to 'Edit', edit_phone_path(@phone) %> |
<%= link_to 'Back', phones_path %>